[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "composer_cluster_policy"
version = "1.0.0"
description = "Airflow Cluster Policies and Governance for Google Cloud Composer"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.entry-points."airflow.policy"]
task_policy = "composer_cluster_policy.policies:task_policy"
dag_policy = "composer_cluster_policy.policies:dag_policy"
pod_mutation_hook = "composer_cluster_policy.policies:pod_mutation_hook"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = [
    "E501",  # line-too-long
]
