# This is a basic workflow to help you get started with Actions

name: Cloud Composer Diff CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # adapted from GitHub docs for building and testing Python
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      # and strategies used in Python samples 
      # https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/noxfile-template.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-import-order flake8-annotations pytest
      #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --show-source --builtin=gettext --max-complexity=29 --import-order-style=google --ignore=E121,E123,E126,E203,E226,E24,E266,E501,E704,W503,W504,I202 --max-line-length=88
      #- name: Test with pytest
      #  run: |
      #    pytest
